### ISSUE TITLE
Doesn't build on Windows 10

### ISSUE THREAD

**Issue by robert-dzikowski** [icexin/gocraft#24]
I know that Windows isn't supported, but could you help me with this build error, please:
```
λ go build
package github.com/icexin/gocraft
        imports github.com/go-gl/gl/v3.3-core/gl: build constraints exclude all Go files in C:\Users\Robert\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20190320180904-bf2b1f2f34d7\v3.3-core\gl
package github.com/icexin/gocraft
        imports github.com/go-gl/glfw/v3.2/glfw: build constraints exclude all Go files in C:\Users\Robert\go\pkg\mod\github.com\go-gl\glfw@v0.0.0-20200222043503-6f7a984d4dc4\v3.2\glfw
```

**Comment by icexin** [comment]
I'll find some time to find a windows computer to try

**Comment by robert-dzikowski** [comment]
That problem doesn't occur in latest version of glfw, 3.3 (github.com/go-gl/glfw/v3.3/glfw), but it occurs in all versions of gl.

**Comment by icexin** [comment]
I have tried with mingw64 on Windows 10, all is ok.

**Comment by robert-dzikowski** [comment]
It works now. I used GCC from https://winlibs.com and set CGO_ENABLED=1.
